policy:
  approval:
  - or:
    - Internal dependency update
    - Dependabot update
    - Code change

approval_rules:
- name: Internal dependency update
  requires:
    count: 0
  if:
    only_has_contributors_in:
      users:
      - "dependabot[bot]"
      - "renovate-coop-norge[bot]"
    from_branch:
      pattern: "^renovate/(github\\.com-coopnorge-|coopnorge-|engineering-docker-images).*$"
    only_changed_files:
      paths:
      - "^go.mod$"
      - "^go.sum$"
      - "^.github/workflows/.*$"
      - "^docker-compose/Dockerfile$"
    has_valid_signatures_by_keys:
      key_ids: ["B5690EEEBB952194"]

- name: Dependabot update
  requires:
    count: 1
    teams:
    - "coopnorge/engineering"
  options:
    invalidate_on_push: true
    request_review:
      enabled: true
      mode: all-users
    methods:
      github_review: true
  if:
    only_has_contributors_in:
      users:
      - "dependabot[bot]"
      - "renovate-coop-norge[bot]"
    only_changed_files:
      paths:
      - "^go.mod$"
      - "^go.sum$"
      - "^.github/workflows/.*$"
      - "^docker-compose/Dockerfile$"
    has_valid_signatures_by_keys:
      key_ids: ["B5690EEEBB952194"]

- name: Code change
  if:
    changed_files:
      paths:
        - ".*"
  requires:
    count: 2
    teams:
    - "coopnorge/engineering"
  options:
    invalidate_on_push: true
    request_review:
      enabled: true
      mode: random-users
    methods:
      github_review: true
