policy:
  approval:
  - or:
    - Internal dependency update
    - Dependency updates
    - Code change

approval_rules:
- name: Internal dependency update
  requires:
    count: 0
  if:
    only_has_contributors_in:
      users:
      - "dependabot[bot]"
      - "renovate-coop-norge[bot]"
    from_branch:
      pattern: "^renovate/(github\\.com-coopnorge-|coopnorge-|engineering-docker-images).*$"
    only_changed_files:
      paths:
      - "(^|.*/)go\\.mod$"
      - "(^|.*/)go\\.sum$"
      - "(^|.*/)[^/]*Dockerfile[^/]*$"
      - "(^|.*/)docker-compose\\.ya?ml$"
      - "^\\.github/workflows/.*$"
      - "^\\.github/actions/.*$"
    has_valid_signatures_by_keys:
      key_ids: ["B5690EEEBB952194"]

- name: Dependency updates
  requires:
    count: 1
    teams:
    - "coopnorge/backend-and-platform-engineering"
  options:
    invalidate_on_push: true
    request_review:
      enabled: true
      mode: random-users
      count: 8
    methods:
      github_review: true
  if:
    only_has_contributors_in:
      users:
      - "dependabot[bot]"
      - "renovate-coop-norge[bot]"
    only_changed_files:
      paths:
      - "(^|.*/)go\\.mod$"
      - "(^|.*/)go\\.sum$"
      - "(^|.*/)[^/]*Dockerfile[^/]*$"
      - "(^|.*/)docker-compose\\.ya?ml$"
      - "^\\.github/workflows/.*$"
      - "^\\.github/actions/.*$"
    has_valid_signatures_by_keys:
      key_ids: ["B5690EEEBB952194"]

- name: Code change
  if:
    changed_files:
      paths:
      - ".*"
  requires:
    count: 2
    teams:
    - "coopnorge/backend-and-platform-engineering"
  options:
    invalidate_on_push: true
    request_review:
      enabled: true
      mode: random-users
      count: 8
    methods:
      github_review: true
