services:
  devtools:
    build:
      context: .
      dockerfile: Dockerfile.devtools
    working_dir: /srv/workspace
    volumes:
      - .:/srv/workspace:z
      - xdg-cache-home:/root/.cache
      - devtools-var:/srv/workspace/var
    command: [make, watch]
volumes:
    xdg-cache-home: {}
    devtools-var: {}
