FROM golang:1.18.0-buster@sha256:e4950365f46f107ba92f8a9557defccb38f151a79fd5453e9424ec34de08c35d

SHELL ["/bin/bash", "-o", "pipefail", "-c"]

COPY Makefile *.sha256sum /tmp/bootstrap/

ENV PROJECT_TOOLS_DIR=/usr/local/bin/

RUN cd /tmp/bootstrap/ \
    && make toolchain GOFLAGS=
