FROM golang:1.19.0-buster@sha256:89af3595ee9986afca0eeecbad140876480a49479f1cb1e4d10c363b97a11e91

SHELL ["/bin/bash", "-o", "pipefail", "-c"]

COPY Makefile *.sha256sum /tmp/bootstrap/

ENV PROJECT_TOOLS_DIR=/usr/local/bin/

RUN cd /tmp/bootstrap/ \
    && make toolchain GOFLAGS=
