FROM golang:1.19.5-buster@sha256:33d767d032a989ba380e6448b512e9b7056a29a3efbf0409427fdd8445f392e5

SHELL ["/bin/bash", "-o", "pipefail", "-c"]

COPY Makefile *.sha256sum /tmp/bootstrap/

ENV PROJECT_TOOLS_DIR=/usr/local/bin/

RUN cd /tmp/bootstrap/ \
    && make toolchain GOFLAGS=
