name: CI
on:
  pull_request: {}
  push:
    branches:
      - main

jobs:

  mage:
    uses: coopnorge/mage/.github/workflows/mage.yaml@main
    permissions:
      contents: read
      id-token: write
      packages: read
    secrets: inherit

  techdocs:
    permissions:
      contents: read
      id-token: write
      packages: read
      pull-requests: read
    name: TechDocs
    uses: coopnorge/github-workflow-techdocs/.github/workflows/techdocs.yaml@v0

  build:
    needs:
      - mage
      - techdocs
    if: always()
    runs-on: ubuntu-24.04
    steps:
      - run: exit 1
        name: "Catch errors"
        if: |
          needs.mage.result == 'failure' ||
          needs.techdocs.result == 'failure'
    permissions: {}
