# https://docs.github.com/en/actions/learn-github-actions/workflow-syntax-for-github-actions
on:
  push:
    branches: ["main"]
  pull_request:
    branches: ["main"]
  workflow_dispatch:
env:
  XDG_CACHE_HOME: ${{ github.workspace }}/cache
name: validate
jobs:
  validate:
    runs-on: ubuntu-20.04
    strategy:
      matrix:
        go-version: ["1.16", "1.17"]
    permissions:
      contents: read
      issues: write
    steps:
      - name: Cache xdg
        uses: actions/cache@v3
        with:
          path: ${{ env.XDG_CACHE_HOME }}
          key: xdg-v1-${{ hashFiles('**/Makefile') }}
          restore-keys: |
            xdg-v1-
      - uses: actions/checkout@v4
        with:
          fetch-depth: 0
      - uses: actions/setup-go@v3
        with:
          go-version: ${{matrix.go-version}}
      - shell: bash
        run: |
          make VERBOSE=all toolchain validate publish-coverage
  build:
    needs: ["validate"]
    runs-on: ubuntu-20.04
    steps:
      - shell: bash
        run: |
          echo DONE
